### ISSUE TITLE
Compass: Cardnal directions are wrong

### ISSUE THREAD

**Issue by Cynosphere** [DyaMetR/holohud#5]
North is 90, not 0 and so on. Compared with wherever the top of your spray is when sprayed on the floor.

North: 90
South: -90
East: 0
West: 180/-180

**Comment by DyaMetR** [comment]
Thanks. To be honest I didn't have much criteria when setting up the cardinal directions. I'll keep the issue open until I release the update that fixes this.

**Comment by DyaMetR** [comment]
Okay I realised that I'm taking too long and I just should add a simple patch in the meantime. I'll get to work on it whenever I can.

Thanks for your patience.

**Comment by DyaMetR** [comment]
Fixed in [1.6.6](https://github.com/DyaMetR/H0L-D4/commit/ee6180344b186dd49c8da157a86d37d963452ffb)
